### ISSUE TITLE
Minor error output issue: all is write_1d

### ISSUE THREAD

**Issue by mathomp4** [geospace-code/nc4fortran#1]
**Describe the bug**

This is a simple one as I was looking over your code. Mainly in `writer.F90` there are lines like:
https://github.com/geospace-code/nc4fortran/blob/f93cadbd114a3014cb7c2f0f463be95e5768411d/src/writer.f90#L91

that were copy-pasted. But every one says `write_1d` even if it's for `nc_write_2d` or `nc_write_7d`

**Comment by scivision** [comment]
Thank you. writer.f90 and reader.f90 were turned into generated template files in nc4fortran v0.5.1 so this issue disappeared as a result. Please let us know if there's any features you'd like to see or any other issues.
